# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31241b06011ebe892f72cd941b7b4f5926c061e2790be614ef409e36d6b1fd508799a780b2d401d17fd001275341b958927f1c4d2ba2ef98aea4dc143d95e877

test:
  secret_key_base: f30ef91423093604eac5223cbaea8c6ac2da30d71456c62fdfb68ea7672ff89e50d28f744c559faed75effb515017dde586aa648414cd38e5d67699c992acea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
